name: Deploy app to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install turbo repo
        run: npm install -g turbo

      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Build the app
        run: cd frontend && turbo build

      - name: Copy admin dist to output directory
        run: |
          mkdir -p ./output/admin
          cp -r ./frontend/apps/admin/dist/* ./output/admin/

      - name: Copy admin dist to output directory
        run: |
          mkdir -p ./output/mobile
          cp -r ./frontend/apps/mobile/dist/* ./output/mobile/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
